In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("adult.csv")

print(df.head())

   age workclass  fnlwgt     education  education.num marital.status  \
0   90         ?   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66         ?  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                  ?  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                  ?      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States

In [4]:
print("Task 1")
print("Rows and Columns:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

Task 1
Rows and Columns: (32561, 15)

Column Names:
['age', 'workclass', 'fnlwgt', 'education', 'education.num', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'capital.gain', 'capital.loss', 'hours.per.week', 'native.country', 'income']


In [6]:
age_array = df["age"].to_numpy()
hours_array = df["hours.per.week"].to_numpy()

print("Age NumPy Array:")
print(age_array[:10])

print("\nHours-per-week NumPy Array:")
print(hours_array[:10])

print("\nData types:")
print("Age:", age_array.dtype)
print("Hours-per-week:", hours_array.dtype)

Age NumPy Array:
[90 82 66 54 41 34 38 74 68 41]

Hours-per-week NumPy Array:
[40 18 40 40 40 45 40 20 40 60]

Data types:
Age: int64
Hours-per-week: int64


In [7]:

print("First age:", age_array[0])
print("Second age:", age_array[1])
print("First working hours:", hours_array[0])
print("Second working hours:", hours_array[1])

First age: 90
Second age: 82
First working hours: 40
Second working hours: 18


In [8]:
basic_slice = age_array[0:10]

print("Basic Slicing - first 10 ages:")
print(basic_slice)

Basic Slicing - first 10 ages:
[90 82 66 54 41 34 38 74 68 41]


In [9]:
fancy_index = age_array[[0, 5, 10, 15, 20]]

print("Fancy Indexing:")
print(fancy_index)

Fancy Indexing:
[90 34 45 46 37]


In [17]:
print("Task 2")
age_array = df["age"].to_numpy()

hours_array = df["hours.per.week"].to_numpy()

scaled_value = age_array * (hours_array / 40)

print("First 10 age values:")
print(age_array[:10])

print("\nFirst 10 hours-per-week values:")
print(hours_array[:10])

print("\nFirst 10 derived values:")
print(scaled_value[:10])

Task 2
First 10 age values:
[90 82 66 54 41 34 38 74 68 41]

First 10 hours-per-week values:
[40 18 40 40 40 45 40 20 40 60]

First 10 derived values:
[90.   36.9  66.   54.   41.   38.25 38.   37.   68.   61.5 ]


In [15]:
loop_result = []

for i in range(len(age_array)):
    loop_result.append(age_array[i] * (hours_array[i] / 40))

print("First 10 loop results:")
print(loop_result[:10])

First 10 loop results:
[np.float64(90.0), np.float64(36.9), np.float64(66.0), np.float64(54.0), np.float64(41.0), np.float64(38.25), np.float64(38.0), np.float64(37.0), np.float64(68.0), np.float64(61.5)]


In [16]:
print(np.allclose(scaled_value, loop_result))
%timeit age_array * (hours_array / 40)
%timeit [age_array[i] * (hours_array[i] / 40) for i in range(len(age_array))]

True
306 μs ± 8.82 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
33.3 ms ± 2.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
print("task 3")
filtered_data = df[
    (df["age"] > 40) &
    (df["education"] == "Bachelors") &
    (df["hours.per.week"] > 40)
]

print("Filtered Dataset:")
print(filtered_data.head(10))

print("\nNumber of matching records:", len(filtered_data))

task 3
Filtered Dataset:
     age         workclass  fnlwgt  education  education.num  \
33    51           Private  123011  Bachelors             13   
40    44           Private  326232  Bachelors             13   
45    48           Private  121253  Bachelors             13   
70    49           Private  199029  Bachelors             13   
73    55      Self-emp-inc  227856  Bachelors             13   
75    42           Private  154374  Bachelors             13   
85    44  Self-emp-not-inc  201742  Bachelors             13   
88    55      Self-emp-inc  298449  Bachelors             13   
93    62      Self-emp-inc   56248  Bachelors             13   
109   47           Private  148995  Bachelors             13   

            marital.status       occupation   relationship   race     sex  \
33                Divorced  Exec-managerial  Not-in-family  White    Male   
40                Divorced  Exec-managerial      Unmarried  White    Male   
45   Married-spouse-absent            S

In [19]:
print(filtered_data[
    ["age", "education", "hours.per.week", "income"]
].head(10))

     age  education  hours.per.week income
33    51  Bachelors              50   >50K
40    44  Bachelors              50   >50K
45    48  Bachelors              70   >50K
70    49  Bachelors              55   >50K
73    55  Bachelors              50   >50K
75    42  Bachelors              60   >50K
85    44  Bachelors              50   >50K
88    55  Bachelors              50   >50K
93    62  Bachelors              60   >50K
109   47  Bachelors              60   >50K


In [20]:
print("Age condition:", (filtered_data["age"] > 40).all())
print("Education condition:", (filtered_data["education"] == "Bachelors").all())
print("Hours condition:", (filtered_data["hours.per.week"] > 40).all())

Age condition: True
Education condition: True
Hours condition: True


In [22]:
df = pd.read_csv("adult.csv")

In [23]:
import os
os.makedirs("Output_Files", exist_ok=True)
filtered_data.to_csv(
    "Output_Files/filtered_dataset.csv",
    index=False
)
print("Filtered dataset saved successfully.")

Filtered dataset saved successfully.


In [24]:
print("task 4")
grouped_data = df.groupby(
    "education",
    as_index=False
)["hours.per.week"].mean()

print("GroupBy Result:")
print(grouped_data)

task 4
GroupBy Result:
       education  hours.per.week
0           10th       37.052519
1           11th       33.925957
2           12th       35.780600
3        1st-4th       38.255952
4        5th-6th       38.897898
5        7th-8th       39.366873
6            9th       38.044747
7     Assoc-acdm       40.504217
8      Assoc-voc       41.610709
9      Bachelors       42.614006
10     Doctorate       46.973366
11       HS-grad       40.575374
12       Masters       43.836332
13     Preschool       36.647059
14   Prof-school       47.425347
15  Some-college       38.852284


In [25]:
grouped_data.to_csv(
    "Output_Files/groupby_result.csv",
    index=False
)

grouped_data.to_excel(
    "Output_Files/groupby_result.xlsx",
    index=False
)

print("CSV and XLSX files saved successfully.")

CSV and XLSX files saved successfully.


In [32]:
csv_data = pd.read_csv(
    "Output_Files/groupby_result.csv")
xlsx_data = pd.read_excel(
    "Output_Files/groupby_result.xlsx")
print("CSV Data:")
print(csv_data.head())
print("\nXLSX Data:")
print(xlsx_data.head())

CSV Data:
  education  hours.per.week
0      10th       37.052519
1      11th       33.925957
2      12th       35.780600
3   1st-4th       38.255952
4   5th-6th       38.897898

XLSX Data:
  education  hours.per.week
0      10th       37.052519
1      11th       33.925957
2      12th       35.780600
3   1st-4th       38.255952
4   5th-6th       38.897898


In [31]:
print("CSV Data Types:")
print(csv_data.dtypes)
print("\nXLSX Data Types:")
print(xlsx_data.dtypes)

CSV Data Types:
education          object
hours.per.week    float64
dtype: object

XLSX Data Types:
education          object
hours.per.week    float64
dtype: object


In [29]:
print("Same shape:", csv_data.shape == xlsx_data.shape)
print("Same values:", csv_data.equals(xlsx_data))

Same shape: True
Same values: False


In [38]:
print("task 5")
income_counts = df["income"].value_counts()
print("Income Value Counts:")
print(income_counts)

task 5
Income Value Counts:
income
<=50K    24720
>50K      7841
Name: count, dtype: int64


In [39]:
income_percentage = df["income"].value_counts(normalize=True) * 100
print("Income Percentage Distribution:")
print(income_percentage.round(2))

Income Percentage Distribution:
income
<=50K    75.92
>50K     24.08
Name: proportion, dtype: float64


In [40]:
majority_count = income_counts.max()
minority_count = income_counts.min()
imbalance_ratio = majority_count / minority_count
print("Majority class count:", majority_count)
print("Minority class count:", minority_count)
print("Imbalance ratio:", round(imbalance_ratio, 2))

Majority class count: 24720
Minority class count: 7841
Imbalance ratio: 3.15


In [36]:
dominant_class = income_counts.idxmax()
dominant_percentage = income_percentage.max()

print("Dominant value:", dominant_class)
print("Dominant percentage:", round(dominant_percentage, 2), "%")

Dominant value: <=50K
Dominant percentage: 75.92 %


In [37]:
print("Complete it")

Complete it
